// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: carEnumProto/carEnum.proto

package carEnumProto

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CarEnum service

func NewCarEnumEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CarEnum service

type CarEnumService interface {
	// 根据指定类型获取枚举结果, 支持："Color"、"BodyType"、"Transmission"、"Seat"
	// 返回：common.Response -> Data = common.PagedList {
	//                  List<Any> = List<KeyValueDto>
	//              }
	GetCarEnum(ctx context.Context, in *EnumTypeDto, opts ...client.CallOption) (*common.Response, error)
}

type carEnumService struct {
	c    client.Client
	name string
}

func NewCarEnumService(name string, c client.Client) CarEnumService {
	return &carEnumService{
		c:    c,
		name: name,
	}
}

func (c *carEnumService) GetCarEnum(ctx context.Context, in *EnumTypeDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarEnum.GetCarEnum", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CarEnum service

type CarEnumHandler interface {
	// 根据指定类型获取枚举结果, 支持："Color"、"BodyType"、"Transmission"、"Seat"
	// 返回：common.Response -> Data = common.PagedList {
	//                  List<Any> = List<KeyValueDto>
	//              }
	GetCarEnum(context.Context, *EnumTypeDto, *common.Response) error
}

func RegisterCarEnumHandler(s server.Server, hdlr CarEnumHandler, opts ...server.HandlerOption) error {
	type carEnum interface {
		GetCarEnum(ctx context.Context, in *EnumTypeDto, out *common.Response) error
	}
	type CarEnum struct {
		carEnum
	}
	h := &carEnumHandler{hdlr}
	return s.Handle(s.NewHandler(&CarEnum{h}, opts...))
}

type carEnumHandler struct {
	CarEnumHandler
}

func (h *carEnumHandler) GetCarEnum(ctx context.Context, in *EnumTypeDto, out *common.Response) error {
	return h.CarEnumHandler.GetCarEnum(ctx, in, out)
}
