// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: report/report.proto

package reportProto

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Report service

func NewReportEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Report service

type ReportService interface {
	// 根据leadId获取report的damage信息
	// 返回：common.Response -> List<Any> = List<ReconditionDto>
	GetDamageInfo(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error)
	// 对指定pointId的检测点做整备
	// 返回：common.Response  -> List = nil
	DoPointRecondition(ctx context.Context, in *PointReconditionDto, opts ...client.CallOption) (*common.Response, error)
	// 绑定Damage图片
	// 返回：common.Response -> List = nil
	BindDamagePhotos(ctx context.Context, in *DamagePhotoDto, opts ...client.CallOption) (*common.Response, error)
	// 解绑Damage图片
	// 返回：common.Response -> List = nil
	UnbindDamagePhotos(ctx context.Context, in *DamagePhotoDto, opts ...client.CallOption) (*common.Response, error)
}

type reportService struct {
	c    client.Client
	name string
}

func NewReportService(name string, c client.Client) ReportService {
	return &reportService{
		c:    c,
		name: name,
	}
}

func (c *reportService) GetDamageInfo(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Report.GetDamageInfo", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportService) DoPointRecondition(ctx context.Context, in *PointReconditionDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Report.DoPointRecondition", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportService) BindDamagePhotos(ctx context.Context, in *DamagePhotoDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Report.BindDamagePhotos", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportService) UnbindDamagePhotos(ctx context.Context, in *DamagePhotoDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Report.UnbindDamagePhotos", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Report service

type ReportHandler interface {
	// 根据leadId获取report的damage信息
	// 返回：common.Response -> List<Any> = List<ReconditionDto>
	GetDamageInfo(context.Context, *common.IdDto, *common.Response) error
	// 对指定pointId的检测点做整备
	// 返回：common.Response  -> List = nil
	DoPointRecondition(context.Context, *PointReconditionDto, *common.Response) error
	// 绑定Damage图片
	// 返回：common.Response -> List = nil
	BindDamagePhotos(context.Context, *DamagePhotoDto, *common.Response) error
	// 解绑Damage图片
	// 返回：common.Response -> List = nil
	UnbindDamagePhotos(context.Context, *DamagePhotoDto, *common.Response) error
}

func RegisterReportHandler(s server.Server, hdlr ReportHandler, opts ...server.HandlerOption) error {
	type report interface {
		GetDamageInfo(ctx context.Context, in *common.IdDto, out *common.Response) error
		DoPointRecondition(ctx context.Context, in *PointReconditionDto, out *common.Response) error
		BindDamagePhotos(ctx context.Context, in *DamagePhotoDto, out *common.Response) error
		UnbindDamagePhotos(ctx context.Context, in *DamagePhotoDto, out *common.Response) error
	}
	type Report struct {
		report
	}
	h := &reportHandler{hdlr}
	return s.Handle(s.NewHandler(&Report{h}, opts...))
}

type reportHandler struct {
	ReportHandler
}

func (h *reportHandler) GetDamageInfo(ctx context.Context, in *common.IdDto, out *common.Response) error {
	return h.ReportHandler.GetDamageInfo(ctx, in, out)
}

func (h *reportHandler) DoPointRecondition(ctx context.Context, in *PointReconditionDto, out *common.Response) error {
	return h.ReportHandler.DoPointRecondition(ctx, in, out)
}

func (h *reportHandler) BindDamagePhotos(ctx context.Context, in *DamagePhotoDto, out *common.Response) error {
	return h.ReportHandler.BindDamagePhotos(ctx, in, out)
}

func (h *reportHandler) UnbindDamagePhotos(ctx context.Context, in *DamagePhotoDto, out *common.Response) error {
	return h.ReportHandler.UnbindDamagePhotos(ctx, in, out)
}
