// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: carLogProto/car_log.proto

package carLogProto

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CarLog service

func NewCarLogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CarLog service

type CarLogService interface {
	// 获取指定车辆id的log信息，返回 data：PageList {
	//            List = List<CarLogResp>
	//          }
	List(ctx context.Context, in *CarLogReq, opts ...client.CallOption) (*common.Response, error)
}

type carLogService struct {
	c    client.Client
	name string
}

func NewCarLogService(name string, c client.Client) CarLogService {
	return &carLogService{
		c:    c,
		name: name,
	}
}

func (c *carLogService) List(ctx context.Context, in *CarLogReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarLog.List", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CarLog service

type CarLogHandler interface {
	// 获取指定车辆id的log信息，返回 data：PageList {
	//            List = List<CarLogResp>
	//          }
	List(context.Context, *CarLogReq, *common.Response) error
}

func RegisterCarLogHandler(s server.Server, hdlr CarLogHandler, opts ...server.HandlerOption) error {
	type carLog interface {
		List(ctx context.Context, in *CarLogReq, out *common.Response) error
	}
	type CarLog struct {
		carLog
	}
	h := &carLogHandler{hdlr}
	return s.Handle(s.NewHandler(&CarLog{h}, opts...))
}

type carLogHandler struct {
	CarLogHandler
}

func (h *carLogHandler) List(ctx context.Context, in *CarLogReq, out *common.Response) error {
	return h.CarLogHandler.List(ctx, in, out)
}
