// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: carCampaignProto/carCampaign.proto

package carCampaignProto

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CarCampaign service

func NewCarCampaignEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CarCampaign service

type CarCampaignService interface {
	// 添加活动，返回 data：nil
	Add(ctx context.Context, in *CarCampaignReq, opts ...client.CallOption) (*common.Response, error)
	// 删除指定活动，返回 data：nil
	Delete(ctx context.Context, in *DeleteCarCampaignReq, opts ...client.CallOption) (*common.Response, error)
	// 获取指定id的活动详情：返回 data: CarCostDetailProtoDto
	Get(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error)
	// 查询活动列表：返回 Data = common.PageList{
	//              List = List<CarCampaignList>
	//          }
	List(ctx context.Context, in *ListCarCampaignReq, opts ...client.CallOption) (*common.Response, error)
	// 更新活动，返回 data：nil
	Update(ctx context.Context, in *CarCampaignReq, opts ...client.CallOption) (*common.Response, error)
}

type carCampaignService struct {
	c    client.Client
	name string
}

func NewCarCampaignService(name string, c client.Client) CarCampaignService {
	return &carCampaignService{
		c:    c,
		name: name,
	}
}

func (c *carCampaignService) Add(ctx context.Context, in *CarCampaignReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carCampaignService) Delete(ctx context.Context, in *DeleteCarCampaignReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.Delete", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carCampaignService) Get(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.Get", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carCampaignService) List(ctx context.Context, in *ListCarCampaignReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.List", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carCampaignService) Update(ctx context.Context, in *CarCampaignReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.Update", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CarCampaign service

type CarCampaignHandler interface {
	// 添加活动，返回 data：nil
	Add(context.Context, *CarCampaignReq, *common.Response) error
	// 删除指定活动，返回 data：nil
	Delete(context.Context, *DeleteCarCampaignReq, *common.Response) error
	// 获取指定id的活动详情：返回 data: CarCostDetailProtoDto
	Get(context.Context, *common.IdDto, *common.Response) error
	// 查询活动列表：返回 Data = common.PageList{
	//              List = List<CarCampaignList>
	//          }
	List(context.Context, *ListCarCampaignReq, *common.Response) error
	// 更新活动，返回 data：nil
	Update(context.Context, *CarCampaignReq, *common.Response) error
}

func RegisterCarCampaignHandler(s server.Server, hdlr CarCampaignHandler, opts ...server.HandlerOption) error {
	type carCampaign interface {
		Add(ctx context.Context, in *CarCampaignReq, out *common.Response) error
		Delete(ctx context.Context, in *DeleteCarCampaignReq, out *common.Response) error
		Get(ctx context.Context, in *common.IdDto, out *common.Response) error
		List(ctx context.Context, in *ListCarCampaignReq, out *common.Response) error
		Update(ctx context.Context, in *CarCampaignReq, out *common.Response) error
	}
	type CarCampaign struct {
		carCampaign
	}
	h := &carCampaignHandler{hdlr}
	return s.Handle(s.NewHandler(&CarCampaign{h}, opts...))
}

type carCampaignHandler struct {
	CarCampaignHandler
}

func (h *carCampaignHandler) Add(ctx context.Context, in *CarCampaignReq, out *common.Response) error {
	return h.CarCampaignHandler.Add(ctx, in, out)
}

func (h *carCampaignHandler) Delete(ctx context.Context, in *DeleteCarCampaignReq, out *common.Response) error {
	return h.CarCampaignHandler.Delete(ctx, in, out)
}

func (h *carCampaignHandler) Get(ctx context.Context, in *common.IdDto, out *common.Response) error {
	return h.CarCampaignHandler.Get(ctx, in, out)
}

func (h *carCampaignHandler) List(ctx context.Context, in *ListCarCampaignReq, out *common.Response) error {
	return h.CarCampaignHandler.List(ctx, in, out)
}

func (h *carCampaignHandler) Update(ctx context.Context, in *CarCampaignReq, out *common.Response) error {
	return h.CarCampaignHandler.Update(ctx, in, out)
}
