// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: purchasePaymentApproval/purchasePaymentApproval.proto

package purchasePaymentApproval

import (
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ApprovalScanDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApprovalScanDto) Reset() {
	*x = ApprovalScanDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purchasePaymentApproval_purchasePaymentApproval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalScanDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalScanDto) ProtoMessage() {}

func (x *ApprovalScanDto) ProtoReflect() protoreflect.Message {
	mi := &file_purchasePaymentApproval_purchasePaymentApproval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalScanDto.ProtoReflect.Descriptor instead.
func (*ApprovalScanDto) Descriptor() ([]byte, []int) {
	return file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescGZIP(), []int{0}
}

var File_purchasePaymentApproval_purchasePaymentApproval_proto protoreflect.FileDescriptor

var file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDesc = []byte{
	0x0a, 0x35, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x61, 0x72, 0x1a, 0x39, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x64, 0x2d,
	0x62, 0x6a, 0x2f, 0x62, 0x32, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x74, 0x6f, 0x32, 0x4b, 0x0a, 0x17, 0x50, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x14, 0x2e,
	0x63, 0x61, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x53, 0x63, 0x61, 0x6e,
	0x44, 0x74, 0x6f, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x64, 0x2d, 0x62, 0x6a, 0x2f,
	0x62, 0x32, 0x63, 0x2d, 0x63, 0x61, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescOnce sync.Once
	file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescData = file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDesc
)

func file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescGZIP() []byte {
	file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescOnce.Do(func() {
		file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescData = protoimpl.X.CompressGZIP(file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescData)
	})
	return file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDescData
}

var file_purchasePaymentApproval_purchasePaymentApproval_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_purchasePaymentApproval_purchasePaymentApproval_proto_goTypes = []interface{}{
	(*ApprovalScanDto)(nil), // 0: car.ApprovalScanDto
	(*common.Response)(nil), // 1: common.Response
}
var file_purchasePaymentApproval_purchasePaymentApproval_proto_depIdxs = []int32{
	0, // 0: car.PurchasePaymentApproval.Scan:input_type -> car.ApprovalScanDto
	1, // 1: car.PurchasePaymentApproval.Scan:output_type -> common.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchasePaymentApproval_purchasePaymentApproval_proto_init() }
func file_purchasePaymentApproval_purchasePaymentApproval_proto_init() {
	if File_purchasePaymentApproval_purchasePaymentApproval_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_purchasePaymentApproval_purchasePaymentApproval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalScanDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchasePaymentApproval_purchasePaymentApproval_proto_goTypes,
		DependencyIndexes: file_purchasePaymentApproval_purchasePaymentApproval_proto_depIdxs,
		MessageInfos:      file_purchasePaymentApproval_purchasePaymentApproval_proto_msgTypes,
	}.Build()
	File_purchasePaymentApproval_purchasePaymentApproval_proto = out.File
	file_purchasePaymentApproval_purchasePaymentApproval_proto_rawDesc = nil
	file_purchasePaymentApproval_purchasePaymentApproval_proto_goTypes = nil
	file_purchasePaymentApproval_purchasePaymentApproval_proto_depIdxs = nil
}
