// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: carProfile/carProfile.proto

package carProfile

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CarProfile service

func NewCarProfileEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CarProfile service

type CarProfileService interface {
	// 解析车辆资料
	Analysis(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error)
	// 获取车辆资料
	Detail(ctx context.Context, in *CarProfileCond, opts ...client.CallOption) (*common.Response, error)
}

type carProfileService struct {
	c    client.Client
	name string
}

func NewCarProfileService(name string, c client.Client) CarProfileService {
	return &carProfileService{
		c:    c,
		name: name,
	}
}

func (c *carProfileService) Analysis(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarProfile.Analysis", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carProfileService) Detail(ctx context.Context, in *CarProfileCond, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarProfile.Detail", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CarProfile service

type CarProfileHandler interface {
	// 解析车辆资料
	Analysis(context.Context, *common.EmptyDto, *common.Response) error
	// 获取车辆资料
	Detail(context.Context, *CarProfileCond, *common.Response) error
}

func RegisterCarProfileHandler(s server.Server, hdlr CarProfileHandler, opts ...server.HandlerOption) error {
	type carProfile interface {
		Analysis(ctx context.Context, in *common.EmptyDto, out *common.Response) error
		Detail(ctx context.Context, in *CarProfileCond, out *common.Response) error
	}
	type CarProfile struct {
		carProfile
	}
	h := &carProfileHandler{hdlr}
	return s.Handle(s.NewHandler(&CarProfile{h}, opts...))
}

type carProfileHandler struct {
	CarProfileHandler
}

func (h *carProfileHandler) Analysis(ctx context.Context, in *common.EmptyDto, out *common.Response) error {
	return h.CarProfileHandler.Analysis(ctx, in, out)
}

func (h *carProfileHandler) Detail(ctx context.Context, in *CarProfileCond, out *common.Response) error {
	return h.CarProfileHandler.Detail(ctx, in, out)
}
