// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: carCampaign/carCampaign.proto

package carCampaign

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CarCampaign service

func NewCarCampaignEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CarCampaign service

type CarCampaignService interface {
	// 获取当前生效的限时活动，返回 data：nil
	GetCurrentActiveCampaign(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error)
}

type carCampaignService struct {
	c    client.Client
	name string
}

func NewCarCampaignService(name string, c client.Client) CarCampaignService {
	return &carCampaignService{
		c:    c,
		name: name,
	}
}

func (c *carCampaignService) GetCurrentActiveCampaign(ctx context.Context, in *common.IdDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CarCampaign.GetCurrentActiveCampaign", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CarCampaign service

type CarCampaignHandler interface {
	// 获取当前生效的限时活动，返回 data：nil
	GetCurrentActiveCampaign(context.Context, *common.IdDto, *common.Response) error
}

func RegisterCarCampaignHandler(s server.Server, hdlr CarCampaignHandler, opts ...server.HandlerOption) error {
	type carCampaign interface {
		GetCurrentActiveCampaign(ctx context.Context, in *common.IdDto, out *common.Response) error
	}
	type CarCampaign struct {
		carCampaign
	}
	h := &carCampaignHandler{hdlr}
	return s.Handle(s.NewHandler(&CarCampaign{h}, opts...))
}

type carCampaignHandler struct {
	CarCampaignHandler
}

func (h *carCampaignHandler) GetCurrentActiveCampaign(ctx context.Context, in *common.IdDto, out *common.Response) error {
	return h.CarCampaignHandler.GetCurrentActiveCampaign(ctx, in, out)
}
